---
title: "Setup and Materials"
---

### Installing materials locally

We will provide a link to a Posit Cloud space for the workshop.
However, we recommend also installing the materials locally so you have two options.

To install the required packages and course materials, we have an R package called {[causalworkshop](https://github.com/malcolmbarrett/causalworkshop)} to help you do that!
You can install {[causalworkshop](https://github.com/r-causal/causalworkshop)} from GitHub with:

``` r
install.packages("pak")
pak::pak("r-causal/causalworkshop")
```

Once you've installed the package, install the workshop with

``` r
causalworkshop::install_workshop()
```

By default, this package downloads the materials to a conspicuous place like your Desktop.
You can also tell `install_workshop()` exactly where to put the materials:

``` r
causalworkshop::install_workshop("a/path/on/your/computer")
```

You can also find the materials on the [workshop repository](https://github.com/r-causal/causal_inference_r_workshop).

## Posit Cloud workspace

A public cloud workspace with all materials and packages installed is also available on [Posit Cloud](https://posit.cloud/content/1975583).
*Note that for certain workshops, we may provide a custom link to a cloud workspace.*

## Hosted slides

Following the above instructions will download a PDF copy of the slides.
If you'd like to see the HTML version of the slides, we recommend taking a look at the hosted versions rather than the raw versions in the repository.

### Slides

-   [00 Intro](https://causal-inference-r-workshop.netlify.app/00-intro.html)
-   [01 Whole Game](https://causal-inference-r-workshop.netlify.app/01-causal_modeling_whole_game.html)
-   [02 When Standard Methods Succeed](https://causal-inference-r-workshop.netlify.app/02-when-standard-methods-succeed.html)
-   [03 Causal Inference with `group_by` and `summarise`](https://causal-inference-r-workshop.netlify.app/03-causal-inference-with-group-by-and-summarise.html)
-   [04 Causal Diagrams](https://causal-inference-r-workshop.netlify.app/04-dags.html)
-   [05 Causal Inference is Not Just a Statistics Problem](https://causal-inference-r-workshop.netlify.app/05-quartets.html)
-   [06 Introduction to Propensity Scores](https://causal-inference-r-workshop.netlify.app/06-pscores.html)
-   [07 Using Propensity Scores](https://causal-inference-r-workshop.netlify.app/07-using-pscores.html)
-   [08 Checking Propensity Scores](https://causal-inference-r-workshop.netlify.app/08-pscore-diagnostics.html)
-   [09 Fitting the outcome model](https://causal-inference-r-workshop.netlify.app/09-outcome-model.html)
-   [10 Continuous Exposures and G-Computation](https://causal-inference-r-workshop.netlify.app/10-continuous-g-comp.html)
-   [11 Tipping Point Sensitivity Analyses](https://causal-inference-r-workshop.netlify.app/11-tipr.html)
-   [12 Whole Game (Your Turn)](https://causal-inference-r-workshop.netlify.app/12-whole_game-2.html)
-   [13 Bonus: Selection Bias](https://causal-inference-r-workshop.netlify.app/13-bonus-selection-bias.html)
-   [14 Bonus: Continous Exposures with Propensity Scores](https://causal-inference-r-workshop.netlify.app/14-bonus-continuous-pscores.html)
